"""empty message

Revision ID: 243ca22e2543
Revises: 7f333acc0ed0
Create Date: 2019-12-24 13:09:49.533215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243ca22e2543'
down_revision = '7f333acc0ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
