"""empty message

Revision ID: 2c8ac34768ff
Revises: ead935b2042b
Create Date: 2020-01-03 11:30:38.838691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c8ac34768ff'
down_revision = 'ead935b2042b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
