"""empty message

Revision ID: 54b8dcc4c851
Revises: 15cdc8379861
Create Date: 2020-01-03 11:44:52.997904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b8dcc4c851'
down_revision = '15cdc8379861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String(length=50)), nullable=False))
    op.add_column('Artist', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('Artist', sa.Column('state', sa.String(length=2), nullable=False))
    op.add_column('Venue', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('Venue', sa.Column('state', sa.String(length=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'state')
    op.drop_column('Venue', 'name')
    op.drop_column('Artist', 'state')
    op.drop_column('Artist', 'name')
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
