"""empty message

Revision ID: ead935b2042b
Revises: 9745d26ea45e
Create Date: 2020-01-01 18:47:29.938144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead935b2042b'
down_revision = '9745d26ea45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'genres',
                existing_type=sa.ARRAY(sa.VARCHAR(length=50)),
                nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'genres',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
